baseURL: https://hugo-toha.github.io

languageCode: en
title: "Dev-Min Blog"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/

# default Language
defaultContentLanguage: ko

languages:
  ko:
    languageName: Korea
    weight: 1
  # en:
  #   languageName: English
  #   weight: 2
  

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:

  background: /images/sections/site/background.jpg
  # GitHub repo URL of your site
  # gitRepo: https://github.com/DevMinGeonPark/DevMinGeonPark.github.io

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false #가능해 질때 사용하기
    provider: mailchimp
    mailchimpURL: https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e

markup:
  goldmark:
    renderer:
      unsafe: true


disqusShortname: devmingeonpark